# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import library_pb2 as library__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in library_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LibraryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoanByIsbn = channel.unary_unary(
                '/library.LibraryService/LoanByIsbn',
                request_serializer=library__pb2.LoanByIsbnRequest.SerializeToString,
                response_deserializer=library__pb2.LoanResponse.FromString,
                _registered_method=True)
        self.LoanByTitle = channel.unary_unary(
                '/library.LibraryService/LoanByTitle',
                request_serializer=library__pb2.LoanByTitleRequest.SerializeToString,
                response_deserializer=library__pb2.LoanResponse.FromString,
                _registered_method=True)
        self.QueryByIsbn = channel.unary_unary(
                '/library.LibraryService/QueryByIsbn',
                request_serializer=library__pb2.QueryByIsbnRequest.SerializeToString,
                response_deserializer=library__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.ReturnByIsbn = channel.unary_unary(
                '/library.LibraryService/ReturnByIsbn',
                request_serializer=library__pb2.ReturnRequest.SerializeToString,
                response_deserializer=library__pb2.ReturnResponse.FromString,
                _registered_method=True)


class LibraryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoanByIsbn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoanByTitle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryByIsbn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnByIsbn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoanByIsbn': grpc.unary_unary_rpc_method_handler(
                    servicer.LoanByIsbn,
                    request_deserializer=library__pb2.LoanByIsbnRequest.FromString,
                    response_serializer=library__pb2.LoanResponse.SerializeToString,
            ),
            'LoanByTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.LoanByTitle,
                    request_deserializer=library__pb2.LoanByTitleRequest.FromString,
                    response_serializer=library__pb2.LoanResponse.SerializeToString,
            ),
            'QueryByIsbn': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryByIsbn,
                    request_deserializer=library__pb2.QueryByIsbnRequest.FromString,
                    response_serializer=library__pb2.QueryResponse.SerializeToString,
            ),
            'ReturnByIsbn': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnByIsbn,
                    request_deserializer=library__pb2.ReturnRequest.FromString,
                    response_serializer=library__pb2.ReturnResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.LibraryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.LibraryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LibraryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoanByIsbn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/LoanByIsbn',
            library__pb2.LoanByIsbnRequest.SerializeToString,
            library__pb2.LoanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoanByTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/LoanByTitle',
            library__pb2.LoanByTitleRequest.SerializeToString,
            library__pb2.LoanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryByIsbn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/QueryByIsbn',
            library__pb2.QueryByIsbnRequest.SerializeToString,
            library__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnByIsbn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ReturnByIsbn',
            library__pb2.ReturnRequest.SerializeToString,
            library__pb2.ReturnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
