# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: library.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'library.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\x12\x07library\"2\n\x11LoanByIsbnRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"4\n\x12LoanByTitleRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"A\n\x0cLoanResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0c\x64ue_date_iso\x18\x03 \x01(\t\"\"\n\x12QueryByIsbnRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"H\n\rQueryResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x18\n\x10\x63opies_available\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\".\n\rReturnRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"-\n\x0eReturnResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x99\x02\n\x0eLibraryService\x12?\n\nLoanByIsbn\x12\x1a.library.LoanByIsbnRequest\x1a\x15.library.LoanResponse\x12\x41\n\x0bLoanByTitle\x12\x1b.library.LoanByTitleRequest\x1a\x15.library.LoanResponse\x12\x42\n\x0bQueryByIsbn\x12\x1b.library.QueryByIsbnRequest\x1a\x16.library.QueryResponse\x12?\n\x0cReturnByIsbn\x12\x16.library.ReturnRequest\x1a\x17.library.ReturnResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOANBYISBNREQUEST']._serialized_start=26
  _globals['_LOANBYISBNREQUEST']._serialized_end=76
  _globals['_LOANBYTITLEREQUEST']._serialized_start=78
  _globals['_LOANBYTITLEREQUEST']._serialized_end=130
  _globals['_LOANRESPONSE']._serialized_start=132
  _globals['_LOANRESPONSE']._serialized_end=197
  _globals['_QUERYBYISBNREQUEST']._serialized_start=199
  _globals['_QUERYBYISBNREQUEST']._serialized_end=233
  _globals['_QUERYRESPONSE']._serialized_start=235
  _globals['_QUERYRESPONSE']._serialized_end=307
  _globals['_RETURNREQUEST']._serialized_start=309
  _globals['_RETURNREQUEST']._serialized_end=355
  _globals['_RETURNRESPONSE']._serialized_start=357
  _globals['_RETURNRESPONSE']._serialized_end=402
  _globals['_LIBRARYSERVICE']._serialized_start=405
  _globals['_LIBRARYSERVICE']._serialized_end=686
# @@protoc_insertion_point(module_scope)
